upstream gateway_backends {
        # 该地址是 k8s 中的 gateway 的 service 地址和端口 
        # server sunitscloud-microservice-gateway-jar-svc.dev.svc:9201 max_fails=3 fail_timeout=30s;
        server gateway.sc.sunits.net max_fails=3 fail_timeout=30s;
}
server {
    listen       80;
    access_log /dev/stdout json;
    error_log /dev/stderr error;

    location / {
        root   /sunits/sunits-ui;
        try_files $uri $uri/ /index.html;
        index  index.html index.htm;
    }

    location /dev-api/{
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://gateway_backends;
    }

    location /stage-api/{
        rewrite ^/stage-api/(.*)$ /$1 break;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://gateway_backends;
    }

    location /websocket/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://gateway_backends;
    }

    # 避免actuator暴露
    if ($request_uri ~ "/actuator") {
        return 403;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}
